# Generated by Django 4.2.1 on 2023-05-05 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hoteles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hotel', models.CharField(max_length=50)),
                ('habitaciones', models.IntegerField()),
                ('precio_camapauno', models.FloatField()),
                ('estrellas', models.IntegerField()),
                ('precio_camapado', models.FloatField()),
                ('wifi', models.BooleanField()),
                ('servicio_al_cuarto', models.BooleanField()),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestadores.prestadores')),
            ],
        ),
    ]
