# Generated by Django 4.2.1 on 2023-05-26 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0002_place_type_delete_hoteles_delete_prestadores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='types',
            new_name='type',
        ),
    ]
